trigger:
  - master

strategy:
  matrix:
    windows-stable:
      image: windows-2019
      style: 'unflagged'
    windows-nightly-canary:
      image: windows-2019
      style: 'canary'

pool:
  vmImage: $(image)

steps:
  - bash: |
      set -e
      rustup update
      rustc -Vv
      echo "##vso[task.prependpath]$HOME/.cargo/bin"
      rustup component add rustfmt
    displayName: Install Rust
  - bash: RUSTFLAGS="-D warnings" cargo test --all
    condition: eq(variables['style'], 'unflagged')
    displayName: Run tests
  - bash: RUSTFLAGS="-D warnings" cargo clippy --all -- -D clippy::result_unwrap_used -D clippy::option_unwrap_used
    condition: eq(variables['style'], 'unflagged')
    displayName: Check clippy lints
  - bash: NUSHELL_ENABLE_ALL_FLAGS=1 RUSTFLAGS="-D warnings" cargo test --all
    condition: eq(variables['style'], 'canary')
    displayName: Run tests
  - bash: NUSHELL_ENABLE_ALL_FLAGS=1 RUSTFLAGS="-D warnings" cargo clippy --all -- -D clippy::result_unwrap_used -D clippy::option_unwrap_used
    condition: eq(variables['style'], 'canary')
    displayName: Check clippy lints
  - bash: cargo fmt --all -- --check
    condition: eq(variables['style'], 'fmt')
    displayName: Lint
